name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: ./.nvmrc

      - run: npm ci
      - run: node --run build

      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          registry-url: https://registry.npmjs.org

      - name: Publish to Public NPM
        run: npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_TOKEN }}

      - run: npx changelogen gh release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
